version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "jest"
  ]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"
