name: 'Clubhouse: Update pull request'

on:
   pull_request:
      types: [opened, reopened]

jobs:
   update:
      runs-on: ubuntu-latest
      steps:
         - uses: farmersdog/clubhouse-pr@v2.0.0
           with:
              ghToken: ${{ secrets.GITHUB_TOKEN }}
              chToken: ${{ secrets.CLUBHOUSE_TOKEN }}
