name: "Clubhouse Labeler"
on:
  pull_request:
    types: [labeled, unlabeled, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: amblerhq/gh-actions-clubhouse-labeler@v1
        with:
          ghToken: ${{ secrets.GH_TOKEN_FOR_CLUBHOUSE }}
          chToken: ${{ secrets.CLUBHOUSE_TOKEN }}
