name: 'Clubhouse: Labeler'
on:
   pull_request:
      types: [labeled, unlabeled]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: amblerhq/gh-actions-clubhouse-labeler@v1
           with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              clubhouse-token: ${{ secrets.CLUBHOUSE_TOKEN}}
