name: 'Tests: run tests'
on:
   workflow_dispatch:
   pull_request:
      types: [opened, reopened, ready_for_review, synchronize]
jobs:
   checkout:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v2

   yarn_cache:
      runs-on: ubuntu-latest

      steps:
         - name: 'cache .yarn'
           uses: actions/cache@v2
           with:
              path: ~/.yarn
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

   node_modules:
      runs-on: ubuntu-latest

      steps:
         - name: 'cache node_modules'
           uses: actions/cache@v2
           with:
              path: ~/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

   test:
      runs-on: ubuntu-latest
      needs: [node_modules, checkout, yarn_cache]

      steps:
         - name: 'yarn install'
           run: yarn install --immutable --silent

         - name: 'Run tests'
           run: yarn test
