name: 'Tests: run tests'
on:
   pull_request:
      types: [opened, reopened, ready_for_review, synchronize]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: 'cache .yarn'
           uses: actions/cache@v2
           with:
              path: ~/.yarn
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - name: 'cache node_modules'
           uses: actions/cache@v2
           with:
              path: ~/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - name: 'yarn install'
           run: yarn install --immutable --silent

         - name: 'Run tests'
           run: yarn test
