name: 'Tests: run tests'
on:
   pull_request:
      types: [opened, reopened, ready_for_review, synchronize]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - uses: actions/cache@v2
           id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
           with:
              path: ${{ './.yarn/cache/' }}
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - name: NPM or Yarn install with caching
           uses: bahmutov/npm-install@v1.6.0
           with:
              install-command: yarn install --immutable --silent

         - name: Run tests
           run: yarn test
