name: 'Tests: run tests'
on:
   pull_request:
      types: [opened, reopened, ready_for_review, synchronize]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: 'cache .yarn/cache'
           uses: actions/cache@v2
           with:
              path: ~/.yarn/cache
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

         - name: 'cache node_modules'
           uses: actions/cache@v2
           with:
              path: ~/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

         # - name: NPM or Yarn install with caching
         #   uses: bahmutov/npm-install@v1.6.0
         #   with:
         #      install-command: yarn install --immutable --silent

         - name: yarn install
           run: yarn install --immutable --silent
         - name: Run tests
           run: yarn test
