name: 'Tests: run tests'
on:
   workflow_dispatch:
   pull_request:
      types: [opened, reopened, ready_for_review, synchronize]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: 'cache'
           uses: actions/cache@v2
           with:
              path: |
                 ~/.yarn
                 ~/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - run: yarn install --immutable --silent

         - run: yarn test
